apiVersion: v1
kind: Service
metadata:
  name: {{ include "octavo.fullname" . }}
  labels: {{- include "octavo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  selector: {{- include "octavo.selectorLabels" . | nindent 4 }}
